### ISSUE TITLE
Peer review - Sanne 5 feb

### ISSUE THREAD

**Issue by sanneduinkerx** [veerleprins/web-app-from-scratch-2021#1]
**Op Repo**
- link staat erin (alleen zoals je vertelde, issues met data inladen)
- read me is geschreven :)

**Op Code**
- Duidelijke flow, na kleine uitleg ;p
- bij fetch.js, ik begrijp wat er gebeurt. Dus als ik het goed begrijp: eerst fetchData importen vanuit andere js. Je geeft de url van de api aan en de api key. En je hebt 2 api links voor de popular en top rated. Bij `createItems`, maak je de elementen aan en vul je in met de data en geef je mee aan de parent, dat is dus ID met popular of rated.
- Alleen hoe wordt de const API_KEY ingevuld? in kan niet zo goed vinden waar de api key zelf staat het getal (misschien omdat dat nieuw voor mij is dat ik het niet snap :) )
- consistency, verschil in `let` en `const`, zelf zou ik gewoon bij `baseURL` een `const` ipv `let` doen. :)
- benamingen duidelijk, ik snap wat je bedoelt!

**Comment by veerleprins** [comment]
Thank you for the feedback 😄 ! In the meantime I have processed this feedback! I now call the API key with the help of a javascript file that is not (yet) placed on github. This file is still in my gitignore :)
