### ISSUE TITLE
Feedback - Sanne 18 feb 

### ISSUE THREAD

**Issue by sanneduinkerx** [veerleprins/web-app-from-scratch-2021#10]
**Demo app:**
- Je demo ziet er tof uit! Leuk concept!
- Fijn dat je alvast een paar films zit op de overview page, zijn dit de populairste horror films of de nieuwste? Misschien kan je dat er nog boven zetten: 'Net uit' bijvoorbeeld. 😄 
- Het zoeken werkt alleen nog niet 🙈 

**ReadMe:**
- Misschien kan je de description boven je table of contents doen als soort inleiding 😊 
- Verder duidelijk! Diagrammen zien er goed uit!
- Ik kreeg zelf als feedback van Joost nog dat je bij de actor diagrammen pijltjes tussen de actors moet plaatsen zodat het duidelijk is wat de dependencies zijn, waar je wat hebt geïmporteerd. 
- En handig dat je een inhoudsopgave hebt om makkelijk te navigeren.

**Code:**
- Goed opgesplitst! Zo blijft het ook overzichtelijk voor jezelf waar alles is. Goed dat je de verschillende pagina's los van elkaar hebt in de views map! 
- In sommige documenten staan nog geen comments, vergeet dat er niet bij te zetten zodat het voor andere ook duidelijk is! 😄 
- Tip: Bij detailPage.js (regel 2) zou je ook body.classList.add kunnen gebruiken ipv de setAttribute als je een Class wilt toevoegen aan de body. 😊 Ik weet zelf niet wat beter is in dit scenario, zelf zou ik voor classList.add gaan 😃 

**Checklist**
- [x] Feedback naar gebruiker toe op de overviewpagina, boven de gerenderde films 'net uit' bv.
- [x] Actor diagram dependencies tussen actors
- [x] ReadMe description boven aan
- [x] Comments binnen je js
- [x] ClassList.add ipv setAttribute (is geen must 😄 )

Verder ziet het er heel netjes uit, goed gestructureerd!

**Comment by veerleprins** [comment]
Thanks for the feedback! I have now adjusted everything! 👍
