### ISSUE TITLE
Feedback 19feb Lotte

### ISSUE THREAD

**Issue by Lottetekulve** [veerleprins/web-app-from-scratch-2021#11]
Love hoe overzichtelijk je readme en je code is. Door je comments en manier van schrijven kan ik als beginner alsnog je code volgen. Ook je styling is super nice, je ziet ook hier dat je er moeite en tijd in hebt gestoken. Kan alleen nog niets doen op je website, maar daar ben je mee bezig gok ik. Verder ziet alles er goed uit.

**Comment by veerleprins** [comment]
Thanks for the feedback!  😄 👍
