### ISSUE TITLE
Fix error: index.js:1 Uncaught SyntaxError: Cannot use import statement outside a module🤓🤓🤓

### ISSUE THREAD

**Issue by Chazzers** [veerleprins/web-app-from-scratch-2021#2]
Had this one as well at first. You fix this by transforming your script tag in your html from:
```html
<script src="./scripts/index.js"></script>
```
to 

```html
<script type="module" src="./scripts/index.js"></script>
```

**Comment by veerleprins** [comment]
If I add this I just get an error! Did you do npm install at the beginning? Maybe that is the reason that you just got the error?
