### ISSUE TITLE
peer review week 2

### ISSUE THREAD

**Issue by SharonV33** [veerleprins/web-app-from-scratch-2021#4]
## Actor en interaction diagram 📈 
het is duidelijk te zien welke actors wat doen in de diagrammen, de flow van de app is goed weergegeven 😸  namen gebruikt in de actor diagram komen nog niet overeen met code

## App structuur en code kwaliteit 👩🏻‍💻 
code is goed te volgen qua flow, geen globale variabelen en algeheel consistent. Scope is dikke prima gebruikt 🆒 

## Data ophalen, manipuleren en tonen 🎥 
Data wordt async ingeldaden. Voor zover ik zie wordt de data niet gemanipuleerd met map filter en reduce. ☹️ content wordt gegenereerd op basis van data 😄  

## States en routes afhandelen 🚗 
Routes worden afgehandeld door een micro library, super nice van die error pagia. in de live versie lijkt dit alleen nog niet te werken❓

**Comment by veerleprins** [comment]
Thank you for the feedback! I have now adjusted everything. 😄 👍
