### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by victorboucher** [veerleprins/web-app-from-scratch-2021#5]
# Repository
- Je readme is al erg uitgebreid. Ik denk alleen dat je je concept wel wat meer uit kan leggen en wat meer kunt vertellen over hoe de API werkt.
- Je actor en interaction diagrammen zien er netjes uit en staan gewoon in je readme! 😄 

# Code
- Ik zie in je app.js dat je helemaal op regel 1 regenerator-runtime importeert. Dit heb je waarschijnlijk gedaan omdat je een error kreeg van Parcel (of een andere applicatie bundler) omdat er iets mis ging met Babel bij het vinden van een polyfill for asynchrone functies. Deze import verandert waarschijnlijk je gebundelde code aangezien je hier iets importeert. Je kunt ook deze regel toevoegen aan je package.json:
```json
  "browserslist": [
    "since 2017-06" 
  ]
```
Of een andere specifieke browser / lijst van browsers. Hiermee pas je je code niet aan en werkt alles alsnog in elke browser op Internet Explorer en Opera na.
- Je mappen/bestanden structuur is echt top! Ziet er super netjes uit en is heel erg duidelijk te lezen. Ik weet precies waar ik moet zijn voor de juiste files/functies. Blijf dat vooral zo doen!
- Je actor diagram is duidelijk ik snap gelijk wat alles hoort te doen. Alleen mis ik hier nog je createElements functie (denk ik?) en heb je nog niet alle functies gemaakt die in je actor diagram hebt staan. Maar dat is niet verkeerd, dan heb je dus al vooruit gedacht wat nice is!
- Je interaction diagram is netjes, je hebt een erg duidelijke en simpele flow. Alleen kan ik hier niet uit herleiden wanneer een gebruiker op de homepage of detailpage komt door de router. Misschien kun je dit nog op de een of andere manier zichtbaar maken?
- Bij je getData functie gebruik je async await. Ik vind dit zelf ook een nette manier om dit te doen, alleen hoorde ik van iemand uit ons groepje dat ze willen dat we dit met promises doen. Ik weet niet zeker of dit klopt maar misschien kun je dit nog checken. Verder is het misschien nice als je ook een variabele aanmaakt voor je 'endpoint', die kan je dan ook misschien opslaan in een soort config file voor je api. Ik heb vernomen dat Joost dit ook netter vindt.
- Je createElements functie is netjes, alleen is de functie niet echt makkelijk te gebruiken voor andere toepassingen. Ik denk dat het fijn is als je dit algemener houdt zodat je het ook later kunt reusen wanneer je iets anders wilt maken dan een lijst met afbeeldingen. (als je naar mijn createElement functie kijkt bijvoorbeeld zie je dat ik dit voor elk soort element kan gebruiken, hierdoor hoef ik in de toekomst minder code te schrijven wanneer ik andere elementen wil renderen vanuit mijn JavaScript).

Lekker bezig, ziet er top uit en je structuur is echt top. Daar kan ik nog een voorbeeld aan nemen 😄

**Comment by veerleprins** [comment]
Thanks for the feedback (especially the part about those browsers I didn't know). I have now adjusted everything! 👍 😄
