### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by Mokerstier** [veerleprins/web-app-from-scratch-2021#6]
https://github.com/veerleprins/web-app-from-scratch-2021/blob/b722cb7537a9de3643312e81eb527e4d82790cc4/src/scripts/app.js#L10-L12

Kan dit weg?
Of ga je dit later nog gebruiken?

Het is een best practice om geen code te pushen naar git die je niet gebruikt.

**Comment by veerleprins** [comment]
I was indeed planning to use these queries, but I did remove it from my comments now! ✅
