### ISSUE TITLE
querySelector suits your needs better

### ISSUE THREAD

**Issue by Mokerstier** [veerleprins/web-app-from-scratch-2021#7]
https://github.com/veerleprins/web-app-from-scratch-2021/blob/b722cb7537a9de3643312e81eb527e4d82790cc4/src/scripts/routes/router.js#L11

Waarschijnlijk kun je hier beter zeggen:
`const body = document.querySelector('body');

Dit voorkomt dat je verderop `body[0]` moet aanspreken.

`.getElementsByTagName("body")` geeft namelijk een `Array` terug en als het goed is heb je `body` maar 1 keer in je HTML staan.

**Comment by veerleprins** [comment]
Oh, I think I wanted to code too quickly! Thank you and has now been updated! ✅
