### ISSUE TITLE
Readme.md aanvullen

### ISSUE THREAD

**Issue by Mokerstier** [veerleprins/web-app-from-scratch-2021#9]
Misschien nog een wishlist en een feature-list toevoegen

Verder mooi project wel, mooi in modules gewerkt en je code is erg netjes en makkelijk te volgen.
Ook je commits zijn erg clean opgezet.

Extra punten: Je zou misschien nog iets kunnen documenteren over code/commit strategie die je toepast?

Ik ben onder de indruk!

**Comment by veerleprins** [comment]
Thank you for the feedback! 👍  I've adjusted the dots except for the commit strategy. Unfortunately I don't have time for that anymore... 😢
